/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_gqweb_com_jni_TestJniCall */

#ifndef _Included_android_gqweb_com_jni_TestJniCall
#define _Included_android_gqweb_com_jni_TestJniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_gqweb_com_jni_TestJniCall
 * Method:    callTestFun
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_gqweb_com_jni_TestJniCall_callTestFun
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
