/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_gqweb_net_jni_SphinxJniCall */

#ifndef _Included_android_gqweb_net_jni_SphinxJniCall
#define _Included_android_gqweb_net_jni_SphinxJniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_gqweb_net_jni_SphinxJniCall
 * Method:    initSphinx
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_gqweb_net_jni_SphinxJniCall_initSphinx
  (JNIEnv *, jobject);

/*
 * Class:     android_gqweb_net_jni_SphinxJniCall
 * Method:    startSphinxRecord
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_gqweb_net_jni_SphinxJniCall_startSphinxRecord
  (JNIEnv *, jobject);

/*
 * Class:     android_gqweb_net_jni_SphinxJniCall
 * Method:    stopSphinxRecord
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_gqweb_net_jni_SphinxJniCall_stopSphinxRecord
  (JNIEnv *, jobject);

/*
 * Class:     android_gqweb_net_jni_SphinxJniCall
 * Method:    getSphinxRecognizedStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_gqweb_net_jni_SphinxJniCall_getSphinxRecognizedStr
  (JNIEnv *, jobject);

/*
 * Class:     android_gqweb_net_jni_SphinxJniCall
 * Method:    destroySphinx
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_gqweb_net_jni_SphinxJniCall_destroySphinx
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
